name: CI Workflow

on:
  push:
    branches:
      - release
      - main
jobs:
  build-test:
    runs-on: ubuntu-latest
    if: ${{ github.ref_name != 'main' }}
    environment: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run set-env.sh
        run: |
          export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
          export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
          export DOCKER_REGISTRY=${{ secrets.DOCKER_REGISTRY }}
          chmod +x ./deployment/pipelines/set-env.sh
          ./deployment/pipelines/set-env.sh

      - name: Run build.sh
        run: |
          chmod +x ./deployment/pipelines/build.sh
          ./deployment/pipelines/build.sh

  build-prod:
    runs-on: ubuntu-latest
    if: ${{ github.ref_name == 'main' }}
    environment: prod

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run set-env.sh
        run: |
          export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
          export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
          export DOCKER_REGISTRY=${{ secrets.DOCKER_REGISTRY }}
          chmod +x ./deployment/pipelines/set-env.sh
          ./deployment/pipelines/set-env.sh

      - name: Run build.sh
        run: |
          chmod +x ./deployment/pipelines/build.sh
          ./deployment/pipelines/build.sh

  deploy-test:
    needs: build-test
    runs-on: ubuntu-latest
    if: ${{ github.ref_name != 'main' }}
    environment: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Run set-env.sh
        run: |
          export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
          export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
          export DOCKER_REGISTRY=${{ secrets.DOCKER_REGISTRY }}
          chmod +x ./deployment/pipelines/set-env.sh
          ./deployment/pipelines/set-env.sh

      - name: Run deploy.sh
        run: |
          chmod +x ./deployment/pipelines/deploy.sh
          ./deployment/pipelines/deploy.sh
      
  deploy-prod:
    needs: build-prod
    runs-on: ubuntu-latest
    if: ${{ github.ref_name == 'main' }}
    environment: prod

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run set-env.sh
        run: |
          export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
          export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
          export DOCKER_REGISTRY=${{ secrets.DOCKER_REGISTRY }}
          chmod +x ./deployment/pipelines/set-env.sh
          ./deployment/pipelines/set-env.sh
      
      - name: Run deploy.sh
        run: |
          chmod +x ./deployment/pipelines/deploy.sh
          ./deployment/pipelines/deploy.sh