name: CI Workflow

on:
  push:
    branches:
      - release
      - main
jobs:
  build-test:
    runs-on: ubuntu-latest
    if: ${{ github.ref_name != 'main' }}
    environment: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1 # Replace with your AWS region

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2


      - name: Run build.sh
        run: |
          chmod +x ./deployment/pipelines/build.sh
          ./deployment/pipelines/build.sh

  build-prod:
    runs-on: ubuntu-latest
    if: ${{ github.ref_name == 'main' }}
    environment: prod

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1 # Replace with your AWS region

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Run build.sh
        run: |
          chmod +x ./deployment/pipelines/build.sh
          ./deployment/pipelines/build.sh

  deploy-test:
    needs: build-test
    runs-on: ubuntu-latest
    if: ${{ github.ref_name != 'main' }}
    environment: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          repository: Jan-Matter/starthack-2025-deployment
          ref: 'release'
          token: ${{ secrets.G_TOKEN }}

      - name: Run k8s_deploy.sh
        run: |
          git config --global user.email "jan.matter@outlook.com"
          git config --global user.name "Jan Matter"

          echo "Updating image tag for deployment $GITHUB_SHA"

          cd helmcharts/starthack-backend-chart
          sed -i "s/^.*image:.*$/image: 046776365295.dkr.ecr.eu-central-1.amazonaws.com\/starthack-test\/api:$GITHUB_SHA/" values.yaml
          git add values.yaml
          git commit -m "Update image tag for deployment $GITHUB_SHA"
          git push origin $GITHUB_REF_NAME
      
  deploy-prod:
    needs: build-prod
    runs-on: ubuntu-latest
    if: ${{ github.ref_name == 'main' }}
    environment: prod

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          repository: Jan-Matter/starthack-2025-deployment
          ref: 'main'
          token: ${{ secrets.G_TOKEN }}

      - name: Run k8s_deploy.sh
        run: |
          git config --global user.email "jan.matter@outlook.com"
          git config --global user.name "Jan Matter"

          echo "Updating image tag for deployment $GITHUB_SHA"

          cd helmcharts/starthack-backend-chart
          sed -i "s/^.*image:.*$/image: 046776365295.dkr.ecr.eu-central-1.amazonaws.com\/starthack-prod\/api:$GITHUB_SHA/" values.yaml
          git add values.yaml
          git commit -m "Update image tag for deployment $GITHUB_SHA"
          git push origin $GITHUB_REF_NAME