name: CI Workflow

on:
  push:
    branches:
      - release
      - main
jobs:
  build-test:
    runs-on: ubuntu-latest
    if: ${{ github.ref_name != 'main' }}
    environment: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1 # Replace with your AWS region

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2


      - name: Run build.sh
        run: |
          chmod +x ./deployment/pipelines/build.sh
          ./deployment/pipelines/build.sh

  build-prod:
    runs-on: ubuntu-latest
    if: ${{ github.ref_name == 'main' }}
    environment: prod

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1 # Replace with your AWS region

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Run build.sh
        run: |
          chmod +x ./deployment/pipelines/build.sh
          ./deployment/pipelines/build.sh

  deploy-test:
    needs: build-test
    runs-on: ubuntu-latest
    if: ${{ github.ref_name != 'main' }}
    environment: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Run k8s_deploy.sh
        run: |
          chmod +x ./deployment/pipelines/k8s_deploy.sh
          ./deployment/pipelines/k8s_deploy.sh
        with:
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
      
  deploy-prod:
    needs: build-prod
    runs-on: ubuntu-latest
    if: ${{ github.ref_name == 'main' }}
    environment: prod

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Run k8s_deploy.sh
        run: |
          chmod +x ./deployment/pipelines/k8s_deploy.sh
          ./deployment/pipelines/k8s_deploy.sh
        with:
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}